server:
  port: ${PORT:8091}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/postgres}
    username: postgres
    password: qqq

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
    contexts: dev
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
