server:
  port: ${PORT:8090}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: root
    password: 123
    driver-class-name: org.postgresql.Driver
    #data: classpath*:populateDB.sql
  kafka:
    consumer:
      group-id: app.1
  sql:
    init:
      mode: always
      schema-locations: classpath*:initDB.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql