version: '3.8'

services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.development
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=users
      - POSTGRES_PASSWORD=123
    volumes:
      - "db-data:/var/lib/postgresql/data"
  backend:
    build:
      context: services/backend
      dockerfile: Dockerfile.development

    environment:
      - PORT=8090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/users
      - JS_URL=http://localhost
    image: 'java-app'
    ports:
      - 8090:8090
    depends_on:
      - postgres

  frontend:
    build:
      context: services/frontend
      dockerfile: Dockerfile.development
    ports:
      - 80:80

volumes:
  db-data: